const products = [
    {
      id: 1,
      name: "Cupcake",
      image: "images/Cupcake.svg",
      prise: 2090,
      quantity: 1,
      priseInCart: 0,
    },
    {
      id: 2,
      name: "Humburger",
      image: "images/Icon.svg",
      prise: 1390,
      quantity: 1,
      priseInCart: 0,
    },
    {
      id: 3,
      name: "Pizza",
      image: "images/Pizza.svg",
      prise: 1450,
      quantity: 1,
      priseInCart: 0,
    },
    {
      id: 4,
      name: "Bitcoin",
      image: "images/Money.svg",
      prise: 2000000,
      quantity: 1,
      priseInCart: 0,
    },
    {
      id: 5,
      name: "Beer",
      image: "images/beer.svg",
      prise: 1590,
      quantity: 1,
      priseInCart: 0,
    },
    {
      id: 6,
      name: "Coffe",
      image: "images/Coffee.svg",
      prise: 1690,
      quantity: 1,
      priseInCart: 0,
    },
  ];
  